site_name: AetherSX2
theme:
  name: material
  logo: assets/aether-logo.png
  favicon: assets/aether-logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
