site_name: AetherSX2
theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)" 
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)" 
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  logo: assets/aether-logo.png
  icon:
    repo: fontawesome/brands/patreon
  favicon: assets/aether-logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - header.autohide
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/JZ7BkeEdrJ
      name: Join our community server on Discord
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/aethersx2
      name: Support the project on Patreon
    - icon: fontawesome/solid/envelope
      link: mailto:tahlreth@gmail.com
      name: Send an email to the developer
copyright: Copyright &copy; 2021 - 2022 Tahlreth, AetherSX2
repo_url: https://www.patreon.com/aethersx2
repo_name: 'Support us on Patreon'
